### ISSUE TITLE
feature: check if <recovery destination> exists before attempting recovery

### ISSUE THREAD

**Issue by gerbrent** [danthem/undelete-btrfs#12]
Would be lovely to have the script verify whether the `<recovery destination>` exists.

This could happen either:
* before the file search commences, or
* before the recovery attempt commences

If `<recovery destination>` does not exist:
* offer an error message prior to attempting data recovery, or 
* offer to create `<recovery destination>`

Currently, if `<recovery destination>` doesn't exist, the user only discovers the problem and requirement once the recovery process has been engaged, and throws `find` errors:

![image](https://user-images.githubusercontent.com/7018928/210295467-c63ea080-9bf5-4f48-912b-871b37912f83.png)

**Comment by danthem** [comment]
Thank you, I've added a check to make sure destination exists and if it doesn't tell the user, it's been committed now (commit 3263fb34b7d8f3e889a087ce1d231056e32658fa). Also added a check to make source source dev exists. I didn't add a prompt where user can have the script create the directory for them, better exit the script and tell user to do it  themselves.
