### ISSUE TITLE
Is this possible?: Convert /dev/sdd[1-5] Ext4 => /dev/sdd [btrfs - whole disk] - without losing data in sdd5 (old /home)

### ISSUE THREAD

**Issue by philiprhoades** [danthem/undelete-btrfs#21]
I have been using Fedora since Core 1 and still have the old HDs and I have kept using ext[234] FSs just for simplicity / consistency up to the current time (F39) - but now I want to experiment with btrfs and I was thinking I could go through the exercise of converting an old SATA boot drive where I am still using /dev/sdd5 (the old /home partition) as one of a few backup partitions / drives for current live data from my workstation and some small servers.

At first I was thinking I could delete ext4 parts 1-4, replace them with a new btrfs partition and then maybe somehow use btrfs-convert to integrate the remaining ext4 part 5 into the new part 1? . . but what I really want to do is create a new btrfs using the _whole_ of the disk (GPT) - but somehow avoid having to spend a LONG time copying back about 4TB (to the 8TB drive) - the only way I could see that possibility working is to somehow do a recovery on the rest of the disk after the newly-created btrfs only takes up part of the beginning of the disk but leaves the old ext4 dirs and files recoverable somehow from near the beginning of the disk to just past halfway on the disk . .

This is just an interesting idea for experimenting with - it is not the end of the world if it is not possible or if it might be possible but difficult and I crash the drive in the experiment . . but I thought this script might offer a solution?

**Comment by danthem** [comment]
This is far beyond the scope of this script and I would not suggest relying on the undelete-btrfs script for such a task. This script is designed as a last resort recovery method if you've lost data accidentally. In your described scenario I doubt the script would be able to find anything, unfortunately the best thing to do is like to copy the data.

**Comment by philiprhoades** [comment]
> In your described scenario I doubt the script would be able to find anything, unfortunately the best thing to do is like to copy the data.

Yep, that is what I did . . thanks for responding.
