### ISSUE TITLE
Need review / testing with newer versions of btrfs-progs

### ISSUE THREAD

**Issue by danthem** [danthem/undelete-btrfs#4]
I wrote this back when 4.15 was the latest version of btrfs-progs,  btrfs-progs 5.2 is the latest version at the time of writing this. 

Need to test and ensure script still works well and explore if there are any new features that can improve chances of recovery.

**Comment by zoqaeski** [comment]
I had the opportunity to use this script tonight, and can confirm it works (almost) perfectly on btrfs-progs 5.4. It was able to recover every file that was accidentally deleted when I mistyped an `rm` command earlier in the evening, though it did appear to hang at times on restoring particularly large files.

**Comment by danthem** [comment]
Thank you for the update @zoqaeski , I'm glad to hear that you were able to recover all the data and that the script runs fine also on newer btrfs progs! I never really got around to trying it myself yet.

You mentioned it appearing to hang on larger files, was this due to the issue you opened? (#5 )

**Comment by zoqaeski** [comment]
Yeah, I opened that issue rather than suggest features in the discussion here.

**Comment by danthem** [comment]
Have tried and tested script on 5.10 without issues. README still mentions 4.15 but I'm working on some cleanups of the script which will be pushed out soon along with updated README. Also looking in to handling issue #5 but have not hit this situation myself. 

Overall the script does work great also on newer btrfs-progs versions, so this issue has served its purpose and will now be closed.
